### PR TITLE
fixed weather

### PR DESCRIPTION
**Pull request by minextu**

### CODE REVIEW

**Comment by miko007** [comment]
what is the intention of this change?
we are experiencing no difference between the two urls

**Comment by minextu** [comment]
The weather widget showed "Wetter ist zur Zeit nicht verfügbar". After I changed the url it worked again. Now both urls are working again all of a sudden.

**Comment by miko007** [comment]
yeah, this is an openweathermap problem, occuring one in a thousand. are you actually using the framework?
this would be exciting, because we couldn't imagine somone would ^^

**Comment by minextu** [comment]
no, i'm only a student ;)

**Pull request closed without merging**
